POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 4549,
  "protocol": "http",
  "name": "Ex4",
  "stubs": [
    {
      "predicates": [
        {
            "equals": { "method": "POST", "path": "/api/login"}
        },

        {
            "equals": {"headers": {"Content-Type": "application/json"}}
        },

        {
            "deepEquals": 
            { 
                "body":
                {
                    "username":"admin",
                    "password":"secret"
                }
            }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 200,
            "headers": { "Content-Type": "application/json" },
            "body":
            {
                "status": "ok", 
                "token": "validtoken"
            }
          }
        }
      ]
    }
  ]
}

### Teste pesquisa
POST http://localhost:4549/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "secret"
}